### ISSUE TITLE
Exclude gestures, classifiers and fingerspelled(excluding compounds) from aslrp data import

### ISSUE THREAD

**Issue by kwasiopoku** [DCS-LCSR/ASL-DAI#104]

**Comment by cneidle** [comment]
Also I think we should exclude IX type signs, so that these would also not get added to the sign bank from our continuous signing data.  (We would leave what we now have from our ASLLVD collection.). SO that would include these signs-- to be eliminated from the list of signs to be imported into the Sign Bank:  
<img width="102" alt="screen shot 2018-10-30 at 2 14 45 pm" src="https://user-images.githubusercontent.com/13629122/47740460-3d5f0f80-dc4e-11e8-81ff-1e9df8158b02.png">

<img width="101" alt="screen shot 2018-10-30 at 2 14 30 pm" src="https://user-images.githubusercontent.com/13629122/47740461-3d5f0f80-dc4e-11e8-984e-626ac1e6d1f3.png">

Also, signs that have agreement prefixes should be added automatically to the signs

<img width="119" alt="screen shot 2018-10-30 at 2 16 47 pm" src="https://user-images.githubusercontent.com/13629122/47740588-844d0500-dc4e-11e8-8cd4-9b38e32a45df.png">

So ideally, for example 1p-ASK:i should be listed under ASK:

<img width="80" alt="screen shot 2018-10-30 at 2 18 26 pm" src="https://user-images.githubusercontent.com/13629122/47740652-b2324980-dc4e-11e8-9704-1b8fa0093132.png">

So we would end up with

ASK
   ASK
   1p-ASK:i
   ASK_2

For this purpose, "i" and "j" are equivalent, so under 1p-ASK:i we should also
include anything like 1p-ASK:j and 1p-ASK:k but there should be a single entry
as above are all of those options.

Happy to discuss when our higher priority items are out of the way :-)

Thanks !!

**Comment by kwasiopoku** [comment]
Done

**Comment by kwasiopoku** [comment]
IX type signs have been removed.  I have made the change to auto add 1p* and 2p* type signs.  Given that there are only 8 of them, I don't know if we should regenerate the entire set of collections.  Going forward, they should be added automatically
