### ISSUE TITLE
Problem with DAI display of translation field in first utterances of SignStream collections

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#60]
For some reason, the translations that are present for U1 in at least two files (and presumably this is more general) fail to be displayed in the DAI.  It's possible that this relates to some other weirdness in SignStream about first utterances.   We have unresolved problems in deleting items at the beginning, and in re-establishing start points for U1, etc., so it might be good to check in with @gregorydimitriadis  about what may be going on here, but... it is weird.

So, for example, there is no translation here (from dai.cs.rutgers.edu):

![screen shot 2018-01-29 at 9 29 31 am](https://user-images.githubusercontent.com/13629122/35633453-43d2f6f4-0677-11e8-9cc3-abc92cc3e7a8.png)

but the SignStream file has the translation:

![screen shot 2018-01-29 at 9 31 56 am](https://user-images.githubusercontent.com/13629122/35633461-49b40bd0-0677-11e8-995b-86c81fe4e66d.png)

Same for the following:

![screen shot 2018-01-29 at 9 33 49 am](https://user-images.githubusercontent.com/13629122/35633482-5e063f18-0677-11e8-9745-d71ec6ac55b3.png)

![screen shot 2018-01-29 at 9 34 56 am](https://user-images.githubusercontent.com/13629122/35633486-620f0efa-0677-11e8-8188-35d5ac5f2b0e.png)

Thanks very much.

**Comment by kwasiopoku** [comment]
@gregorydimitriadis what do you think about this issue.  Is it possible that the translation for the first utterance are being persisted differently than for other utterances in the collection?

**Comment by gregorydimitriadis** [comment]
@kwasiopoku It's possible the U1 translation was getting lost during some issues on the SignStream side, due to how they were being saved in the collection XML. See these issues for more:

https://github.com/DCS-LCSR/SignStream3/issues/90

https://github.com/DCS-LCSR/SignStream3/issues/196

I believe as of the latest SignStream release (v14) that this is resolved (which would mean collections saved after that point and going forward would be okay, but not any which were prior to that) but I'm not sure. It's odd that the SignStream collection Carol is looking at actually has the translation field present.

**Comment by kwasiopoku** [comment]
Carol will re-save collections with SignStream v15.  Once that is completed, we will be able to regenerate the DAI data and verify that the translations are visible in the search results

**Comment by kwasiopoku** [comment]
Re-parsing signstream collection files should address this issue

**Comment by kwasiopoku** [comment]
Fixed
